# This is a TOML configuration file for market_miner.py
[miners]
[miners.trend]
atr_days = 20
volatility_days=90
debug = true
filename = "examples/swing-momentum/trend.py"
index = 'SP500'
indicators = ['SMA100']
portfolio_size = 2000
rank_days = 90
risk_factor = 0.002
